name: Do Not Submit

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Do Not Submit
        uses: chainguard-dev/actions/donotsubmit@b2555de0cf9724fb9b49d050ff18bd1f49562ba7 # v1.6.29
