name: Code Style

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:
  gofmt:
    name: check gofmt
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: './go.mod'
          check-latest: true

      - uses: chainguard-dev/actions/gofmt@71714a76c3df10b544595a2294c16649dc3472e5 # v1.6.5
        with:
          args: -s

  goimports:
    name: check goimports
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: './go.mod'
          check-latest: true

      - uses: chainguard-dev/actions/goimports@71714a76c3df10b544595a2294c16649dc3472e5 # v1.6.5
