name: Whitespace

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:

  whitespace:
    name: Check Whitespace
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: chainguard-dev/actions/trailing-space@bed8050123fff65538e2db1902ff9404030c0221 # v1.6.31
        if: ${{ always() }}

      - uses: chainguard-dev/actions/eof-newline@bed8050123fff65538e2db1902ff9404030c0221 # v1.6.31
        if: ${{ always() }}
