name: Whitespace

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:

  whitespace:
    name: Check Whitespace
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: chainguard-dev/actions/trailing-space@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb # v1.6.28
        if: ${{ always() }}

      - uses: chainguard-dev/actions/eof-newline@fabe4ed3f66ceb5f8ec86ed7ae6d0c945ca362fb # v1.6.28
        if: ${{ always() }}
