name: Whitespace

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: read-all

jobs:

  whitespace:
    name: Check Whitespace
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: chainguard-dev/actions/trailing-space@8bb24c24be6871bee44f19be55ea11e3b2aea3dd # v1.6.11
        if: ${{ always() }}

      - uses: chainguard-dev/actions/eof-newline@8bb24c24be6871bee44f19be55ea11e3b2aea3dd # v1.6.11
        if: ${{ always() }}
